[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' https://js.stripe.com;
      style-src 'self' 'unsafe-inline';
      connect-src 'self' https://fakestoreapi.com;
      img-src 'self' data: https:;
    """

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
